### ISSUE TITLE
CMS Revamp

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#115]
# Description

The goal of the project is to revamp CMS, so that the new CMS fulfilled a minimal feature set of:

1. User List
2. A configurable Entity List
3. Send Push Notification with simply user segment.

# Portal Design

## Portal Features

* Have a CMS tab on the left hand-side:
   * 1st Tab: "Use the CMS" Have an intro page, with beautiful graphical introduction of features / sample to the CMS. Show the URL, and a button to open CMS in new browser. 
   * 2nd Tab: "Customisation" no idea yet.... depends on the config file... maybe a large textarea for the config file first.
   * 3rd Tab: "Access Control", a (mostly) instruction page to explain how role affect CMS user rights. And a simply textbox control to allow assign any username / email with the `cms-admin` role 
   * 4th Tab: "Whitelabel", maybe simply have a big textarea with a default CSS template?

### Wireframe
* User Management: [Skygear CMS - Users.pdf](https://github.com/SkygearIO/features/files/1375743/Skygear.CMS.-.Users.pdf)
* Push Notification: 
![skygear-notifications-old](https://user-images.githubusercontent.com/387241/31481782-be96bd70-af57-11e7-900e-7cfa62f870bb.jpg)

# API Design

## Scenario

Developer would use this feature in either one of the two ways:

1. Writing a site configuration file
2. Configuring site with code (likely javascript or the like)

### Writing a site configuration file

Developer declares their CMS site structure with a config file. The CMS plugin
should load this file and serve a site according to the content of that config file.
Config file is intended to be used in skygear-cloud portal, and also by developers
who are less confident with code / have the most common CMS requirements.

The config file is consist of the following sections:

1. `site`

   Define how the site assembles itself. Site is consist of pages. Here is a possible
   configuration (in YAML):

   ```yaml
   site:
       # Declare a built-in Dashboard page.
     - type: Dashboard
       # Declare a group of pages. It should create a folder in menu with all
       # its children layout as sub-items
     - type: Group
       label: Tables
       children:
           # Declare a page for Record "topic". Record page configuration is defined
           # in the Records section.
         - type: Record
           name: topic
         - type: Record
           name: poll
         - type: Record
           name: question
     - type: PushNotificationPanel
   ```

2. `records`

   Records define records that are mentioned in the `site` section. For every record
   type, four views (list, new, edit and destroy) can be configured.

   Each view consists of a list of fields. Field defines how Skygear data type
   shows its data in corresponding views and how they can be edited (for
   new & edit views).

   See _Built-in field types_ for the list of possible built-in fields for existing
   Skygear data types.

   See [this gist](https://gist.github.com/limouren/1edd2e164eaee2692575cd81bae2d414)
   for a YAML configuration examples.

3. `association_records`

   This section define association records that can be used in Reference and
   BackReference fields in the `records` section. Its main usage is to
   model many-to-many relationship in a relational DB.

   See _Modeling relationship_ for more details on how it is used to represent
   many-to-many relationship.

### Configuring site with code

It is expected that developers would configure CMS with code if:

1. They are more comfortable to work with code directly (i.e. the underlying layer of config file); or
2. They need to write their own custom field / page (which might requires external dependencies); or
3. They were using config file, but config file no longer fulfills their needs
   and they are forced to switch.

To make life of developers in scenario #3 easier, it is expected that a commandline
utility would help convert an existing configuration into a properly code-configured
CMS (probably not in initial phrase).

Code configuration should be a superset of config file in terms of achievable
functionalities.

_Code configuration specs examples / spec missing_

* It depends heavily on frontend stack. I haven't decided on it yet so no examples.
* I have solicited opinions from some colleagues and it seems like react
  has all the votes...

### Built-in field types

Here is a list of field types that I could think of based on existing
Skygear data types. Feel free to comment / add more of them. First level
of the list is Skygear data type:

<table>
  <thead>
    <tr>
      <th>Skygear Built-in Types</th>
      <th>CMS Field Types</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>String</td>
      <td>
        <ul>
          <li>String (single-line string)</li>
          <li>Text (multi-line string)</li>
          <li>Email</li>
          <li>URL
            <ul>
              <li>Image</li>
              <li>Video</li>
            </ul>
          </li>
          <li>(String)Dropdown</li>
          <li>Rich Text
            <ul>
              <li>HTML</li>
              <li>Markdown</li>
            </ul>
          </li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>Number</td>
      <td>
        <ul>
          <li>Int</li>
          <li>Float</li>
          <li>Unix Timestamp</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>Boolean</td>
      <td>Boolean</td>
    </tr>
    <tr>
      <td>JSON</td>
      <td>
        <ul>
          <li>Object</li>
          <li>Array</li>
          <li>(Object)Array (Special control about adding items?)</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>Datetime</td>
      <td>
        <ul>
          <li>Datetime</li>
          <li>Date</li>
          <li>Time (Is it better to model it like a number?)</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>Location</td>
      <td>
        <ul>
          <li>lat-lng Coordinate</li>
          <li>Map</li>
          <li>Address Input?</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>Reference</td>
      <td>
        <ul>
          <li>Reference</li>
          <li>ReferenceArray</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>Asset</td>
      <td>
        <ul>
          <li>Asset</li>
          <li>Image</li>
          <li>Video</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>ACL</td>
      <td>ACL (not in current phrase)</td>
    </tr>
  </tbody>
</table>

#### One-To-One Embedded

Consider two record types `user` and `private_user`.

```yaml
records:
  user:
    list:
      fields:
        - type: _id
        - name: name
          type: String
        - type: EmbeddedRecord
          reference:
            - name: company_id
              type: BackReference
              from: private_user
              fromField: _id  # private_user._id
              toField: _id    # user.id
              isOne: true     # denote that this back reference has only one item
          fields:
              # we need the _id field for reference purpose even if we are not
              # showing it
            - type: _id
              hidden: true
            - name: hk_id
              label: HK ID
              type: String
```

Fields in EmbeddedRecord (`private_user.hk_id`) would be shown like `user`'s fields.

#### One-To-Many

Consider a relationship between `parent` and `child`. One parent could have
many children and one child could have only one parent:

```yaml
records:
  parent:
    list:
      fields:
        - type: _id
        - name: name
          type: String
        - label: Children
          type: BackReference
          from: child
          fromField: parent_id
  child:
    list:
      fields:
        - type: _id
        - name: name
          type: String
        - name: parent_id
          type: String
        - name: parent_id
          label: Parent
          type: Reference
          referencing: parent
```

View behavior:

* list
  * `parent`: Show a link to `child` list with filter `parent_id` = current parent
  * `child`: Show `parent` id with link to its show page
* show
  * `parent`: Show a list of its `child`
  * `child`: same as list
* edit
  * `parent`: Show a table of its `child`ren. Admin could remove children. Might be
    able to add `child` with a button.
    * We probably want some form of filtering on the list of children on addition
  * `child`: Show its `parent` (might be a select). Admin should be able to switch / clear selection.
    * Again, we might want filtering on list of parents being shown.
* new
  * `parent`: A table-like interface to add existing `child` / create `child` in place.
  * `child`: Same as edit.

#### Many-To-Many

Consider two record types `country` and `enterprise`. A `country` can have
to many `enterprise`s and an `enterprise` might exist in multiple `country`.

First we define the record type used for this many-to-many relationship in
`association_records` section:

```yaml
association_records:
  country_enterprise:
    fields:
      - name: country_id
        type: Reference
        referencing: country
        referencingField: _id
      - name: enterprise_id
        type: Reference
        referencing: enterprise
        referencingField: _id
```

Now we can define this relationship in `records` section:

```yaml
records:
  country:
    list:
      fields:
        - type: _id
        - name: name
          type: String
        - name: enterprises
          type: Reference
          referencing: enterprise
          # specify association record instead of referencingField
          via_association_record: country_enterprise
  enterprise:
    list:
      fields:
        - type: _id
        - name: name
          type: String
        - name: countries
          type: Reference
          referencing: country
          via_association_record: country_enterprise

```

View behavior:

View behavior is the same as those of one-to-many _except_ that admin couldn't
create new referencing record in new page & edit page.

### Push Notification Panel

Requirements:

1. Send to all users
2. Send to users of some channels
   * Probably implemented as "Send to users satifying a query, where user.channel is an array"
   * Reuse list filter UI?
     * Developer could configure which fields can be filtered
   * Might need templating with user as context
3. Send to individual user
   * Add an built-in action s.t. admin could do this by pressing a button in list or show page?

# Open Questions

## Future Features

* Localization
  * Basically keep different versions of a field
  * Should be manually enabled for a specific field
  * Fields other than text can also be localized (e.g. Image)
  * Always has a fallback locale
  * Might be good to get locale info from user, but the basic is that caller
    has to supply it in the request (Likely HTTP Header)
  * CMS would need a way to transform Skygear response of record(s),
    probably in Go.

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.
