### ISSUE TITLE
prerender options for deployments for SSR to solve SEO issues

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#310]
# Description

**Add 2-3 sentence description of your feature**

## Scenario

**Put list of Scenario how developers will use this API**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by roxk** [comment]
# Description
- A one-click solution to SEO aimed at SPA
- Serve pre-rendered SPA from cache
- Configurable
    - cache expiry
    - timeout for additional AJAX
    - SEO agent

### Deployment:
```
deployments:
  static-index:
   type: static
   src: index.html
   path: /
   use-prerender-for-seo: true
   prerender-config: prerender-common.yaml
   prerender-expiry: 3600s
   prerender-capture-timeout: 20s 
   prerender-seo-agent: googlebot
```

### `golang`:
`chromedp` to [generate dom](https://github.com/chromedp/chromedp/issues/128)

# Scenario
When the content of a SPA needs SEO

# API Design
Add an attribute `use-prerender-for-seo: bool` to existing CF configuration (Storage format of config doesn't seem to have been specified in [api.md](https://github.com/SkygearIO/features/blob/master/features/268-next-cf/api.md) so I am specifying type here anyways)

### Potential additional attributes:
`prerender-config: text`: path to a `yaml` file that groups other attributes. Or accept string such that people can pipe to it? What is the convention in skygear here?
`prerender-expiry: text`: The amount of time a cached dom is kept. Support postfix time format? Default to 1 day (align to prerender.io)? Do we have a convention for skygear elsewhere?
`prerender-capture-timeout: number`: The amount of time the service wait until it captures the dom. Default to 0, which means the service will capture after the initial batch javascript had run.
`prerender-seo-agent: text`: A comma-separated list of user-agent that would trigger prerender. (Or do we have better format?)

Support configuration overriding, i.e attributes in `deployments` override those which are specified in `prerender-config`?
